service: pokemon-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: 'dev'
  region: 'us-east-1'
  memorySize: 512

functions:
  pokemonFunc:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline